### ISSUE TITLE
Build failed for Android

### ISSUE THREAD

**Issue by Ajaxy** [appodeal/appodeal-cordova-plugin#1]
Такая ошибка:

> :compileDebugJavaWithJavac/project/src/com/appodeal/plugin/AppodealPlugin.java:179: error: method disableNetwork in class Appodeal cannot be applied to given types;
					Appodeal.disableNetwork(network);
					        ^
  required: Context,String
  found: String
  reason: actual and formal argument lists differ in length

**Comment by NazarKozak** [comment]
@Ajaxy уже должно быть исправлено, попробуйте обновить плагин.
