### ISSUE TITLE
[iOS] XCode build errors

### ISSUE THREAD

**Issue by telekosmos** [appodeal/appodeal-cordova-plugin#12]
Hi there
Our environment is:
- OSX 10.11.6
- XCode 8.1
- com.appodeal.plugin 2.1.0

The plugin was added after removing 1.15.2, which didn't display rewarded videos in android. So, we tried version 2.1.0, which seems to work great with android but in iOS environment we get so many errors as seen in the screenshot:
<img width="1401" alt="screen shot 2016-12-07 at 10 32 27" src="https://cloud.githubusercontent.com/assets/1622788/20962653/75d36c90-bc6a-11e6-98f8-431c4102bff4.png">

Any hint about this? Do I have to download the SDK from any other source?

Thanks!!!

**Comment by NazarKozak** [comment]
@telekosmos it looks like 0.10.x Appodeal iOS SDK is used here. 
You don't need to download anything else, plugin is doing all the stuff from version 2.0.
Try to remove and re-add plugin again.
