### ISSUE TITLE
App Transport Security and old plugin ?

### ISSUE THREAD

**Issue by matrixreal** [appodeal/appodeal-cordova-plugin#14]
Hi,
since we use the appodeal plugin version 1.1.4 (wich is stable and the rewarded video is working wihout the white screen problem reported with 2.x version [here](https://github.com/appodeal/appodeal-cordova-plugin/issues/7) ) .... then we need a fix / adaptation for the ats enabled on the old appodeal plugin (1.1.4)
thank you

**Comment by AnnaBai** [comment]
Thanks for the note. We will update it soon. 
Anna

**Comment by NazarKozak** [comment]
@matrixreal We have updated plugin with ATS compatibility. 
White screen issue is `cordova-plugin-statusbar` plugin issue, details here: https://github.com/appodeal/appodeal-cordova-plugin/issues/7 .
