### ISSUE TITLE
Banner overlaps the content

### ISSUE THREAD

**Issue by vintage** [appodeal/appodeal-cordova-plugin#18]
I want to place a banner ad at the bottom of the page, but it overlaps the content of the screen. Is there any option to make it "separate" from the main content of the app? Something like the overlap flag in the https://github.com/sunnycupertino/cordova-plugin-admob-simple ?

I can probably add some margin-bottom to my content, but I don't know exactly what banner height is showing currently. Any solutions?

Screen:

![glass_i_iphone_se_ _ios_10_2__14c89_](https://cloud.githubusercontent.com/assets/729785/22247907/72f0ccdc-e23c-11e6-8298-87bd9a495db7.png)

Under the ad banner I've tabs to switch current view, but it's currently hidden by the banner.

**Comment by meeeeeepo** [comment]
@vintage we are working on it, for now you can set margin-bottom according to the height of banner which equals 50 for iPhone and 90 for iPad

**Comment by vintage** [comment]
@meeeeeepo I've started working on a small new app and the trick with the margin-bottom worked as desired. The banner doesn't overlap my content. I've tried same trick in my bigger apps, but it mess a bit with rest of the styling, didn't have enough time to investigate and check what's happening there. Do you have any roadmap when the functionality will be available in the core plugin? I've seen that there are dedicated branches for it, are they ready to test?

**Comment by meeeeeepo** [comment]
@vintage you can test out branch that in develop now
`cordova plugin add https://github.com/appodeal/appodeal-cordova-plugin#banner_overlaps_ios`
This is not compatible with status-bar-plugin at the moment, but you can test without status bar plugin for now

**Comment by vintage** [comment]
@meeeeeepo I've uninstalled the appodeal plugin and re-added it using `cordova plugin add https://github.com/appodeal/appodeal-cordova-plugin#banner_overlaps_ios`. Does the overlap requires some additional flag in the plugin initialization? I didn't see any difference  between master and this branch.

![img_0378](https://cloud.githubusercontent.com/assets/729785/22795266/5dd7e17a-eef6-11e6-8f40-e7ee385c2808.PNG)

plugin list:

```
com.appodeal.plugin 2.1.0 "Appodeal Plugin"
cordova-plugin-console 1.0.5 "Console"
cordova-plugin-crosswalk-webview 2.3.0 "Crosswalk WebView Engine"
cordova-plugin-device 1.1.4 "Device"
cordova-plugin-device-motion 1.2.3 "Device Motion"
cordova-plugin-inappbrowser 1.6.1 "InAppBrowser"
cordova-plugin-inapppurchase 1.0.0 "In App Purchase"
cordova-plugin-insomnia 4.3.0 "Insomnia (prevent screen sleep)"
cordova-plugin-nativeaudio 3.0.8 "Cordova Native Audio"
cordova-plugin-splashscreen 4.0.1 "Splashscreen"
cordova-plugin-whitelist 1.3.1 "Whitelist"
cordova-sqlite-storage 2.0.2 "Cordova sqlite storage plugin"
ionic-plugin-keyboard 2.2.1 "Keyboard"
me.tonny.cordova.plugins.multidex 0.1.0 "Cordova Multi Dex"
```

**Comment by meeeeeepo** [comment]
@vintage yeah, sorry, you need to do `Appodeal.setBannerOverLap(true)`
And reinstall plugin pls, i fixed cordova source js

**Comment by wo-github** [comment]
I have the same problem with Ionic on Android. There is no setBannerOverLap method.
https://ionicframework.com/docs/native/appodeal/

**Comment by Tamplier** [comment]
@wo-github you need to address this question to ionic team, because they don't have setBannerOverLap method is their wrapper for our plugin:
https://github.com/ionic-team/ionic-native
