### ISSUE TITLE
Invalid banner orientation at first load

### ISSUE THREAD

**Issue by vintage** [appodeal/appodeal-cordova-plugin#19]
The first load of the banner (after platform is ready and additional 5 seconds timeout) has invalid orientation. My whole application is only available in the landscape mode and the banner doesn't seem right at the first load.

```
setTimeout(() => {
    Appodeal.show(engine.BANNER_BOTTOM)
}, 3000);
```

![img_0371](https://cloud.githubusercontent.com/assets/729785/22642655/eabd09dc-ec5b-11e6-94fa-75d596d4d2eb.PNG)

The next one after ad rotation:

![img_0372](https://cloud.githubusercontent.com/assets/729785/22643019/2a063568-ec5d-11e6-9533-7ff01e374da4.PNG)

As you can see the first one seems like it is adjusted to the portrait mode, and then after it rotates (30 seconds?) it display correct size. I've tried to update the Appodeal dashboard to tell that my app supports only landscape:

![appodeal_dashboard](https://cloud.githubusercontent.com/assets/729785/22643201/c8c16f56-ec5d-11e6-8aee-9db52f152277.png)

but it doesn't change anything.

**Comment by allexus39** [comment]
Hi @vintage . This is a normal ad orientation. You have AdMob smart banners on both screenshots. Smart Banners are ad units that render screen-width banner ads on any screen size across different devices in either orientation. When an image ad isn't large enough to take up the entire allotted space, the image will be centered.

**Comment by vintage** [comment]
@allexus39 According to the official AdMob docs - https://firebase.google.com/docs/admob/ios/banner the Smart banner size is `Screen width x 32|50|90` so it have to occupy full width of the device. Additionally docs says:

`Typically, Smart Banner ads on phones are full width x 50dp in portrait and full width x 32dp in landscape` and `When an image ad isn't large enough to take up the entire allotted space, the image is centered and the space on either side is filled in.`. In this case the space is not filled with anything and I can see the app content on the sides, so it leads me to the same thing - the first banner is adjusted to fill the portrait orientation.

**Comment by meeeeeepo** [comment]
@vintage you can set banner background property to true, with that banner view will have background and you son't see app content

**Comment by vintage** [comment]
@meeeeeepo Thanks, the `Appodeal.setBannerBackground(true);` worked as expected.
