### ISSUE TITLE
Incorrect documentation on appodeal.com

### ISSUE THREAD

**Issue by charlesbodman** [appodeal/appodeal-cordova-plugin#2]
Not sure if this is the correct place to put this.

https://www.appodeal.com/sdk/documentation?framework=9&full=1&platform=4

> 5.3. Display ad
To initialize only interstitials use Appodeal.initializeAdType(appKey, Appodeal.INTERSTITIAL)

Should this just be `Appodeal.initialize(appKey, Appodeal.INTERSTITIAL)`?

**Comment by NazarKozak** [comment]
@charlesbodman you are right, it should be just ```initialize```. Sorry for mistake, I've fixed that already.
