### ISSUE TITLE
appendStatus is not defined. (appodeal.js)

### ISSUE THREAD

**Issue by charlesbodman** [appodeal/appodeal-cordova-plugin#3]
https://github.com/appodeal/appodeal-cordova-plugin/blob/master/www/appodeal.js#L30

Missing declaration.

**Comment by charlesbodman** [comment]
I do see what happened. It looks like appendStatus is a debug funtion used in the demo.
https://github.com/appodeal/appodeal-cordova-demo

**Comment by NazarKozak** [comment]
@charlesbodman fixed, please try updated plugin.
