### ISSUE TITLE
Background Thread

### ISSUE THREAD

**Issue by charlesbodman** [appodeal/appodeal-cordova-plugin#31]
Any chance we can move Appodeal to a background thread? 

THREAD WARNING: ['AppodealPlugin'] took '40.682129' ms. Plugin should use a background thread.

**Comment by Tamplier** [comment]
@charlesbodman 
The most part of the work takes place in a background thread, but we need to call some methods in UI thread. That little part, which is executed in the main thread, leads to the warning.
Nothing to worry about.

**Comment by charlesbodman** [comment]
Thanks for the response
