### ISSUE TITLE
sdk updates ?

### ISSUE THREAD

**Issue by matrixreal** [appodeal/appodeal-cordova-plugin#34]
Hi,
any news about updating different network sdk ?
thanks

**Comment by matrixreal** [comment]
any news?

**Comment by NazarKozak** [comment]
Hi! Will be updated with new sdk releases, in around 2 weeks.

**Comment by matrixreal** [comment]
Hi @NazarKozak 
Any news ?
thank you

**Comment by charlesbodman** [comment]
ETA?

**Comment by NazarKozak** [comment]
@charlesbodman @matrixreal till the end of week update will be ready

**Comment by NazarKozak** [comment]
@matrixreal @charlesbodman Hello! Try updated plugin on branch: [cordova2](/appodeal/appodeal-cordova-plugin/tree/cordova2).
