### ISSUE TITLE
Comodo Malware Warning with a the Signed Android App if you use the cordova appodeal-cordova-plugin!

### ISSUE THREAD

**Issue by RonnySchleicher** [appodeal/appodeal-cordova-plugin#46]
## Important NOTE
❗️ The error occurs only when you create a **Signed APK** ❗️ 
If you create a 'normal' APK or a Debug Version is everything okay.

### Systems:
* Windows 10 Pro 64 bit, Core i7, 8GB RAM, all updates installed with Android Studio 2.3.3, Cordova 6.5
* iMac (Retina 5K, 27 Zoll), Core i7, 16GB RAM, macOS Sierra 10.12.6, all updates installed with Android Studio 2.3.3, Cordova 6.5
* Testdevice Nexus 5X with Android 8.0.0 and **Comodo Mobile Security** with the **LATEST** Virus DB update (you should be download inside the comodo app)

#### The Comodo App

![image](https://user-images.githubusercontent.com/1914203/30859066-6759acda-a2c2-11e7-86ba-7264d02dbc54.png)

### Steps to Reproduce (for Windows)
* create a fresh new Android Project, only with the appodeal-cordova-plugin
* use follow script (in this sample for Windows)
```
call cordova create PhoneGap_android de.test.test Test
cd PhoneGap_android
call cordova platform add android
call cordova plugin add https://github.com/appodeal/appodeal-cordova-plugin.git
call cordova plugin ls

pause
```

Open the Project with the Android Studio.

#### First little Problem
The first Error is a minSdkVersion conflict
![image](https://user-images.githubusercontent.com/1914203/29123957-b6eda20e-7d17-11e7-8321-69844c15eed6.png)

I set...
```
android:minSdkVersion="14"
```
...and everything is okay

#### Second Big Problem
If you create an debug or release version of your app and transfer it via usb on your testdevice, everything is okay and works fine. **No Malware warning appears!** 

But if you create a SIGNED APK with a (new generated) keystore file and install it via usb with follow command
```
call adb.exe install "android-release.apk"
```
follow Malware Message appears:

![image](https://user-images.githubusercontent.com/1914203/30859121-9cd0a698-a2c2-11e7-86f9-8d8301078d06.png)

The same behavior happens when the app is installed from the Play-Store ❗️ 

❗️ This is a very big Problem for all Android Apps with the Appodeal Plugin ❗️

**Comment by RonnySchleicher** [comment]
Hello Appodeal.
There are news about the problem?

**Comment by AndriyFliak** [comment]
Hi Ronny. We're investigated the issue and it occurs because Comodo detects Startapp as Malware. Startapp is in contact with Comodo and the issue should be resolved soon

**Comment by RonnySchleicher** [comment]
## I have tried the following workaround:

I removed the startapp-3.6.2.jar in the Android Studio:

![image](https://user-images.githubusercontent.com/1914203/30927789-e498f7d0-a3b9-11e7-9599-b5faeb30ec67.png)

Now the **Comodo Mobile Security** say also is fine.  ✅ 
Also the app and the advertising seem to work without problems. ✅ 

The only thing that is disturbing is a toast message when initializing the Appodeal plugin.

![image](https://user-images.githubusercontent.com/1914203/30928001-873d27cc-a3ba-11e7-83ee-57936b4268b0.png)

### Important questions to the Appodeal Dev Engineers
* Has this workaround any side effects ❓ 
* It is possible to suppress the toast message above ❓

**Comment by Tamplier** [comment]
@RonnySchleicher you can use the following line to disable toast message:
Appodeal.disableNetwork("startapp");
There are no side effects. Of course, Appodeal plugin won't be able to use startapp network in that case.

**Comment by RonnySchleicher** [comment]
### Summary
* remove startapp-3.6.2.jar in the Android Studio
* add Appodeal.disableNetwork("startapp"); in the javascript code

Also is fine! No Malware Warning appears.
Thanks for the help.
