### ISSUE TITLE
Callback firing forever

### ISSUE THREAD

**Issue by Vahn84** [appodeal/appodeal-cordova-plugin#50]
Hi, I recently implemented the appodeal plugin in my Cordova app. 

Everything is fine except for the fact that when a Banner fails to load it seems to keep trying to load again and again, firing "onFailedToLoad" forever

Calling Appodeal.hide() seems to have 0 effects

**Comment by Vahn84** [comment]
From the android logcat:

`11-15 16:24:06.716 21907-21907/com.nextadv.smartphoners I/Ads: Starting ad request.
11-15 16:24:06.717 21907-21907/com.nextadv.smartphoners I/Ads: Use AdRequest.Builder.addTestDevice("B8B853B378E8C36A9506A2A013AF46E6") to get test ads on this device.
11-15 16:24:06.735 21907-6217/com.nextadv.smartphoners D/FA: Logging event (FE): ad_query(_aq), Bundle[{firebase_event_origin(_o)=am, firebase_screen_class(_sc)=MainActivity, firebase_screen_id(_si)=5744207643546989600, ad_event_id(_aeid)=5744207643546989646}]
11-15 16:24:06.987 21907-21927/com.nextadv.smartphoners W/Ads: There was a problem getting an ad response. ErrorCode: 0
11-15 16:24:06.987 21907-21907/com.nextadv.smartphoners W/Ads: Failed to load ad: 0
11-15 16:24:06.988 21907-21907/com.nextadv.smartphoners D/Appodeal: Admob onBannerFailedToLoad, eCPM: 0.20, reason: no fill
11-15 16:24:07.645 21907-21907/com.nextadv.smartphoners D/Appodeal: Applovin onBannerFailedToLoad, eCPM: 0.04, reason: no fill
11-15 16:24:07.647 21907-21907/com.nextadv.smartphoners D/Appodeal: onBannerFailedToLoad`

**Comment by Tamplier** [comment]
@Vahn84 this is auto cache algorithm. The plugin tries to cache banner while your application is working. If you don't want to continue attempts to load an ad, you can use manual caching:
```
Appodeal.setAutoCache(Appodeal.BANNER, false);
Appodeal.initialize(appKey, Appodeal.BANNER);
Appodeal.cache(Appodeal.BANNER);
```

**Comment by Vahn84** [comment]
HI @Tamplier thank you for your support

Am I forced to turn off the autocache before the initialize function, or am I able to turn it off when It fail the first time, and turn it on again the next time it properly loads?

**Comment by Tamplier** [comment]
@Vahn84 yes, unfortunately, you forced to turn off the auto cache before initialization. The disabling or enabling won't work after calling that function.
Yes, you can initialize banners and don't cache they at all. It has no sense, it leads to useless internet traffic (banner waterfall, for example) but you can =)
