### ISSUE TITLE
appodeal and chartboost

### ISSUE THREAD

**Issue by matrixreal** [appodeal/appodeal-cordova-plugin#58]
hi,
i want to buy installs from chartboost (network advertising) for my apps
and i need to install chartboost sdk separatly
how can i do it ?
thank you

**Comment by matrixreal** [comment]
**solution by Yaroslav (Appodeal Team) thanks a lot**

"We have our repository with Cordova mulidex plugin 
https://github.com/appodeal/appodeal-cordova-nodex-plugin
fork it
delete "chartboost.jar" from libs -> Android

delete chartboost mention from plugin.xml

And disable chartboost before sdk initialisation in code: Appodeal.disableNetwork("chartboost");

**Comment by Tamplier** [comment]
@matrixreal 
Yes, Yaroslav is right, but you can also use base (this one) version and multidex version of the plugin.
To remove chartboost in those versions you need open appodeal.jar with your favorite archiver and delete assets/dex/chartboost.dex (or any other network) file.
Also, you still need to disable network with Appodeal.disableNetwork method. No changes in plugin.xml are required.

Feel free to reopen the issue if it's required.

**Comment by matrixreal** [comment]
Hello again,
i have 2 questions :

1- it is same steps to remove others networds ? (examples adcolony)

2- i'm using appodeal multi dex plugin when i open appodeal-2.1.7.jar and search for the path you say i don't find chartboost.dex the folder assets/dex/ is empty.

thanks a lot

**Comment by Tamplier** [comment]
@matrixreal 
We have 3 versions of Appodeal plugin for cordova. Base, maxdex and nodex. There are no dex files in appodeal.jar in case if you use nodex version. In other cases, a network can be located inside appodeal.jar (dex file) or in libs/Android directory (as a jar file). Not in both locations at the same time. 

I just want to say that you can remove any network from any version of our plugin. But in case if the network is represented as a jar file, you should delete a mention about that network from plugin.xml. In case if network is represented as a dex file, you should just open appodeal.jar with any archiver and delete dex file (no need to remove something from plugin.xml).
