### ISSUE TITLE
uses-sdk:minSdkVersion 9 cannot be smaller than version 14 declared in library [android:CordovaLib:unspecified:debug]

### ISSUE THREAD

**Issue by charlesbodman** [appodeal/appodeal-cordova-plugin#8]
We are currently trying to build for one of our apps and getting this error. 

`java.lang.RuntimeException: Manifest merger failed : uses-sdk:minSdkVersion 9 cannot be smaller than version 14 declared in library [android:CordovaLib:unspecified:debug]`

Our cordova config has minSdkVersion set to 15

`<preference name="android-minSdkVersion" value="15"/> `

Any help would be great.

**Comment by Tamplier** [comment]
Hi, @charlesbodman 
Short way:
It looks like minSdkVersion from libs/android/cheetah-mobile/AndroidManifest.xml overrides your android-minSdkVersion. Or your android-minSdkVersion preference is just ignored.
You can just edit AndroidManifest.xml from our libs folder and change minSdkVersion.
Alternatively, you can use the following command to build and run your project:
`cordova run android -- --minSdkVersion=15`

Long way:
We need more information.
1. Full version of your config.xml
2. Do you build your application with cordova CLI? What version do you have?
3. What other plugins do you use?
